### ISSUE TITLE
create deployment failed

### ISSUE THREAD

**Issue by TensShinet** [carina-io/carina#111]
执行完 `./deploy.sh install` 以后，用下面的 yaml 文件创建 Deployment：

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-web-server
  template:
    metadata:
      labels:
        app: test-web-server
    spec:
      containers:
        - name: test-web-server
          image: nginx:latest
          imagePullPolicy: "IfNotPresent"
```

在创建 ReplicaSet 失败：

![image](https://user-images.githubusercontent.com/35733911/184848643-ce6508cd-7765-4db9-9c62-6d63bba1f06d.png)

describe 这个 rs：

![image](https://user-images.githubusercontent.com/35733911/184848791-d52362c5-710e-424d-9aa8-28ad6fe2c404.png)

想知道如何解决这样的错误。谢谢🙏
