### ISSUE TITLE
节点资源够用，但是调度失败

### ISSUE THREAD

**Issue by zwForrest** [carina-io/carina#51]
**What happened**:
pod调度失败

storageclass.yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-carina-sc
provisioner: carina.storage.io
parameters:
  carina.storage.io/disk-type: "vg_hdd"
reclaimPolicy: Delete
allowVolumeExpansion: true
# 创建pvc后立即创建pv,WaitForFirstConsumer表示被容器绑定调度后再创建pv
volumeBindingMode: WaitForFirstConsumer
mountOptions:
```
node注册资源信息
```
allocatable:
    carina.storage.io/vg_hdd: "117"
    carina.storage.io/vg_ssd: "117"
    cpu: 7600m
    ephemeral-storage: 196460520Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: "31225464193"
    mixer.io/ext-cpu: "6237"
    mixer.io/ext-memory: "0"
    mixer.kubernetes.io/ext-cpu: "5837"
    mixer.kubernetes.io/ext-memory: "9958435896"
    pods: "62"
  capacity:
    carina.storage.io/vg_hdd: "128"
    carina.storage.io/vg_ssd: "128"
    cpu: "8"
    ephemeral-storage: 196460520Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 32637492Ki
    mixer.io/ext-cpu: "6237"
    mixer.io/ext-memory: "0"
    mixer.kubernetes.io/ext-cpu: "5837"
    mixer.kubernetes.io/ext-memory: "9958435896"
    pods: "62"

```
csi configmap配置，这里我不需要自动发现，所以匹配没写
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: carina-csi-config
  namespace: kube-system
  labels:
    class: carina
data:
  config.json: |-
    {
      "diskSelector": [
        {
          "name": "vg_ssd" ,
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
        {
          "name": "vg_hdd",
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        }
      ],
      "diskScanInterval": "300",
      "schedulerStrategy": "spreadout"
    }
```

调度器日志
```
I0222 06:32:04.145738       1 storage-plugins.go:69] filter pod: carina-deployment-b6785745d-29ghc, node: tj1-kubekey-test07.kscn
I0222 06:32:04.145771       1 storage-plugins.go:130] mismatch pod: carina-deployment-b6785745d-29ghc, node: tj1-kubekey-test07.kscn, request: 1, capacity: 0
```
可以确定的是节点由足够资源

storageclass
**What you expected to happen**:
pod调度成功
**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 0.9.1
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by antmoveh** [comment]
调度器有可能不是最新的版本，0.9.0版本的调度器是不支持自定义vg组的。

**Comment by zwForrest** [comment]
pvc.yaml
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-carina-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-carina-sc
  volumeMode: Filesystem
```
